#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyCongTrinh.DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCongTrinh_skytech")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertST_customer_group(ST_customer_group instance);
    partial void UpdateST_customer_group(ST_customer_group instance);
    partial void DeleteST_customer_group(ST_customer_group instance);
    partial void InsertST_permission(ST_permission instance);
    partial void UpdateST_permission(ST_permission instance);
    partial void DeleteST_permission(ST_permission instance);
    partial void InsertST_customer(ST_customer instance);
    partial void UpdateST_customer(ST_customer instance);
    partial void DeleteST_customer(ST_customer instance);
    partial void InsertST_department(ST_department instance);
    partial void UpdateST_department(ST_department instance);
    partial void DeleteST_department(ST_department instance);
    partial void InsertST_employee(ST_employee instance);
    partial void UpdateST_employee(ST_employee instance);
    partial void DeleteST_employee(ST_employee instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PhanMemQuanLyCongTrinh.Properties.Settings.Default.QLCongTrinh_skytechConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ST_customer_group> ST_customer_groups
		{
			get
			{
				return this.GetTable<ST_customer_group>();
			}
		}
		
		public System.Data.Linq.Table<ST_permission> ST_permissions
		{
			get
			{
				return this.GetTable<ST_permission>();
			}
		}
		
		public System.Data.Linq.Table<ST_customer> ST_customers
		{
			get
			{
				return this.GetTable<ST_customer>();
			}
		}
		
		public System.Data.Linq.Table<ST_department> ST_departments
		{
			get
			{
				return this.GetTable<ST_department>();
			}
		}
		
		public System.Data.Linq.Table<ST_employee> ST_employees
		{
			get
			{
				return this.GetTable<ST_employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_customer_groups")]
	public partial class ST_customer_group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _customer_group_id;
		
		private string _customer_group_id_custom;
		
		private string _customer_group_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_group_idChanging(long value);
    partial void Oncustomer_group_idChanged();
    partial void Oncustomer_group_id_customChanging(string value);
    partial void Oncustomer_group_id_customChanged();
    partial void Oncustomer_group_nameChanging(string value);
    partial void Oncustomer_group_nameChanged();
    #endregion
		
		public ST_customer_group()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_group_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long customer_group_id
		{
			get
			{
				return this._customer_group_id;
			}
			set
			{
				if ((this._customer_group_id != value))
				{
					this.Oncustomer_group_idChanging(value);
					this.SendPropertyChanging();
					this._customer_group_id = value;
					this.SendPropertyChanged("customer_group_id");
					this.Oncustomer_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_group_id_custom", AutoSync=AutoSync.Always, DbType="VarChar(34)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string customer_group_id_custom
		{
			get
			{
				return this._customer_group_id_custom;
			}
			set
			{
				if ((this._customer_group_id_custom != value))
				{
					this.Oncustomer_group_id_customChanging(value);
					this.SendPropertyChanging();
					this._customer_group_id_custom = value;
					this.SendPropertyChanged("customer_group_id_custom");
					this.Oncustomer_group_id_customChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_group_name", DbType="NVarChar(200)")]
		public string customer_group_name
		{
			get
			{
				return this._customer_group_name;
			}
			set
			{
				if ((this._customer_group_name != value))
				{
					this.Oncustomer_group_nameChanging(value);
					this.SendPropertyChanging();
					this._customer_group_name = value;
					this.SendPropertyChanged("customer_group_name");
					this.Oncustomer_group_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_permissions")]
	public partial class ST_permission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _permission_id;
		
		private string _permission_id_custom;
		
		private string _permission_name_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpermission_idChanging(long value);
    partial void Onpermission_idChanged();
    partial void Onpermission_id_customChanging(string value);
    partial void Onpermission_id_customChanged();
    partial void Onpermission_name_Changing(string value);
    partial void Onpermission_name_Changed();
    #endregion
		
		public ST_permission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this.Onpermission_idChanging(value);
					this.SendPropertyChanging();
					this._permission_id = value;
					this.SendPropertyChanged("permission_id");
					this.Onpermission_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id_custom", AutoSync=AutoSync.Always, DbType="VarChar(32)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string permission_id_custom
		{
			get
			{
				return this._permission_id_custom;
			}
			set
			{
				if ((this._permission_id_custom != value))
				{
					this.Onpermission_id_customChanging(value);
					this.SendPropertyChanging();
					this._permission_id_custom = value;
					this.SendPropertyChanged("permission_id_custom");
					this.Onpermission_id_customChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_name_", DbType="NVarChar(200)")]
		public string permission_name_
		{
			get
			{
				return this._permission_name_;
			}
			set
			{
				if ((this._permission_name_ != value))
				{
					this.Onpermission_name_Changing(value);
					this.SendPropertyChanging();
					this._permission_name_ = value;
					this.SendPropertyChanged("permission_name_");
					this.Onpermission_name_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_customers")]
	public partial class ST_customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _customer_id;
		
		private string _customer_id_custom;
		
		private string _customer_name;
		
		private long _customer_group_id;
		
		private string _customer_address;
		
		private string _customer_email;
		
		private string _custome_phone;
		
		private string _custome_bank_account_number;
		
		private string _custome_tax_code;
		
		private string _customer_description;
		
		private string _customer_liabilities;
		
		private System.Nullable<System.DateTime> _custome_date_of_birth;
		
		private System.Nullable<bool> _custome_gender;
		
		private System.Nullable<System.DateTime> _customer_created_date;
		
		private System.Data.Linq.Binary _customer_image;
		
		private System.Nullable<long> _employee_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_idChanging(long value);
    partial void Oncustomer_idChanged();
    partial void Oncustomer_id_customChanging(string value);
    partial void Oncustomer_id_customChanged();
    partial void Oncustomer_nameChanging(string value);
    partial void Oncustomer_nameChanged();
    partial void Oncustomer_group_idChanging(long value);
    partial void Oncustomer_group_idChanged();
    partial void Oncustomer_addressChanging(string value);
    partial void Oncustomer_addressChanged();
    partial void Oncustomer_emailChanging(string value);
    partial void Oncustomer_emailChanged();
    partial void Oncustome_phoneChanging(string value);
    partial void Oncustome_phoneChanged();
    partial void Oncustome_bank_account_numberChanging(string value);
    partial void Oncustome_bank_account_numberChanged();
    partial void Oncustome_tax_codeChanging(string value);
    partial void Oncustome_tax_codeChanged();
    partial void Oncustomer_descriptionChanging(string value);
    partial void Oncustomer_descriptionChanged();
    partial void Oncustomer_liabilitiesChanging(string value);
    partial void Oncustomer_liabilitiesChanged();
    partial void Oncustome_date_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Oncustome_date_of_birthChanged();
    partial void Oncustome_genderChanging(System.Nullable<bool> value);
    partial void Oncustome_genderChanged();
    partial void Oncustomer_created_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncustomer_created_dateChanged();
    partial void Oncustomer_imageChanging(System.Data.Linq.Binary value);
    partial void Oncustomer_imageChanged();
    partial void Onemployee_createdChanging(System.Nullable<long> value);
    partial void Onemployee_createdChanged();
    #endregion
		
		public ST_customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id_custom", AutoSync=AutoSync.Always, DbType="VarChar(33)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string customer_id_custom
		{
			get
			{
				return this._customer_id_custom;
			}
			set
			{
				if ((this._customer_id_custom != value))
				{
					this.Oncustomer_id_customChanging(value);
					this.SendPropertyChanging();
					this._customer_id_custom = value;
					this.SendPropertyChanged("customer_id_custom");
					this.Oncustomer_id_customChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_name", DbType="NVarChar(255)")]
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				if ((this._customer_name != value))
				{
					this.Oncustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._customer_name = value;
					this.SendPropertyChanged("customer_name");
					this.Oncustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_group_id", DbType="BigInt NOT NULL")]
		public long customer_group_id
		{
			get
			{
				return this._customer_group_id;
			}
			set
			{
				if ((this._customer_group_id != value))
				{
					this.Oncustomer_group_idChanging(value);
					this.SendPropertyChanging();
					this._customer_group_id = value;
					this.SendPropertyChanged("customer_group_id");
					this.Oncustomer_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_address", DbType="NVarChar(255)")]
		public string customer_address
		{
			get
			{
				return this._customer_address;
			}
			set
			{
				if ((this._customer_address != value))
				{
					this.Oncustomer_addressChanging(value);
					this.SendPropertyChanging();
					this._customer_address = value;
					this.SendPropertyChanged("customer_address");
					this.Oncustomer_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_email", DbType="NVarChar(100)")]
		public string customer_email
		{
			get
			{
				return this._customer_email;
			}
			set
			{
				if ((this._customer_email != value))
				{
					this.Oncustomer_emailChanging(value);
					this.SendPropertyChanging();
					this._customer_email = value;
					this.SendPropertyChanged("customer_email");
					this.Oncustomer_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custome_phone", DbType="NVarChar(30)")]
		public string custome_phone
		{
			get
			{
				return this._custome_phone;
			}
			set
			{
				if ((this._custome_phone != value))
				{
					this.Oncustome_phoneChanging(value);
					this.SendPropertyChanging();
					this._custome_phone = value;
					this.SendPropertyChanged("custome_phone");
					this.Oncustome_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custome_bank_account_number", DbType="NVarChar(30)")]
		public string custome_bank_account_number
		{
			get
			{
				return this._custome_bank_account_number;
			}
			set
			{
				if ((this._custome_bank_account_number != value))
				{
					this.Oncustome_bank_account_numberChanging(value);
					this.SendPropertyChanging();
					this._custome_bank_account_number = value;
					this.SendPropertyChanged("custome_bank_account_number");
					this.Oncustome_bank_account_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custome_tax_code", DbType="NVarChar(100)")]
		public string custome_tax_code
		{
			get
			{
				return this._custome_tax_code;
			}
			set
			{
				if ((this._custome_tax_code != value))
				{
					this.Oncustome_tax_codeChanging(value);
					this.SendPropertyChanging();
					this._custome_tax_code = value;
					this.SendPropertyChanged("custome_tax_code");
					this.Oncustome_tax_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_description", DbType="VarChar(255)")]
		public string customer_description
		{
			get
			{
				return this._customer_description;
			}
			set
			{
				if ((this._customer_description != value))
				{
					this.Oncustomer_descriptionChanging(value);
					this.SendPropertyChanging();
					this._customer_description = value;
					this.SendPropertyChanged("customer_description");
					this.Oncustomer_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_liabilities", DbType="VarChar(255)")]
		public string customer_liabilities
		{
			get
			{
				return this._customer_liabilities;
			}
			set
			{
				if ((this._customer_liabilities != value))
				{
					this.Oncustomer_liabilitiesChanging(value);
					this.SendPropertyChanging();
					this._customer_liabilities = value;
					this.SendPropertyChanged("customer_liabilities");
					this.Oncustomer_liabilitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custome_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> custome_date_of_birth
		{
			get
			{
				return this._custome_date_of_birth;
			}
			set
			{
				if ((this._custome_date_of_birth != value))
				{
					this.Oncustome_date_of_birthChanging(value);
					this.SendPropertyChanging();
					this._custome_date_of_birth = value;
					this.SendPropertyChanged("custome_date_of_birth");
					this.Oncustome_date_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custome_gender", DbType="Bit")]
		public System.Nullable<bool> custome_gender
		{
			get
			{
				return this._custome_gender;
			}
			set
			{
				if ((this._custome_gender != value))
				{
					this.Oncustome_genderChanging(value);
					this.SendPropertyChanging();
					this._custome_gender = value;
					this.SendPropertyChanged("custome_gender");
					this.Oncustome_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> customer_created_date
		{
			get
			{
				return this._customer_created_date;
			}
			set
			{
				if ((this._customer_created_date != value))
				{
					this.Oncustomer_created_dateChanging(value);
					this.SendPropertyChanging();
					this._customer_created_date = value;
					this.SendPropertyChanged("customer_created_date");
					this.Oncustomer_created_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary customer_image
		{
			get
			{
				return this._customer_image;
			}
			set
			{
				if ((this._customer_image != value))
				{
					this.Oncustomer_imageChanging(value);
					this.SendPropertyChanging();
					this._customer_image = value;
					this.SendPropertyChanged("customer_image");
					this.Oncustomer_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_created", DbType="BigInt")]
		public System.Nullable<long> employee_created
		{
			get
			{
				return this._employee_created;
			}
			set
			{
				if ((this._employee_created != value))
				{
					this.Onemployee_createdChanging(value);
					this.SendPropertyChanging();
					this._employee_created = value;
					this.SendPropertyChanged("employee_created");
					this.Onemployee_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_departments")]
	public partial class ST_department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _department_id;
		
		private string _department_id_custom;
		
		private string _department_name;
		
		private string _department_unit;
		
		private System.Nullable<decimal> _department_price;
		
		private System.Nullable<int> _department_percentage_overtime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepartment_idChanging(long value);
    partial void Ondepartment_idChanged();
    partial void Ondepartment_id_customChanging(string value);
    partial void Ondepartment_id_customChanged();
    partial void Ondepartment_nameChanging(string value);
    partial void Ondepartment_nameChanged();
    partial void Ondepartment_unitChanging(string value);
    partial void Ondepartment_unitChanged();
    partial void Ondepartment_priceChanging(System.Nullable<decimal> value);
    partial void Ondepartment_priceChanged();
    partial void Ondepartment_percentage_overtimeChanging(System.Nullable<int> value);
    partial void Ondepartment_percentage_overtimeChanged();
    #endregion
		
		public ST_department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id_custom", AutoSync=AutoSync.Always, DbType="VarChar(33)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string department_id_custom
		{
			get
			{
				return this._department_id_custom;
			}
			set
			{
				if ((this._department_id_custom != value))
				{
					this.Ondepartment_id_customChanging(value);
					this.SendPropertyChanging();
					this._department_id_custom = value;
					this.SendPropertyChanged("department_id_custom");
					this.Ondepartment_id_customChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_name", DbType="NVarChar(200)")]
		public string department_name
		{
			get
			{
				return this._department_name;
			}
			set
			{
				if ((this._department_name != value))
				{
					this.Ondepartment_nameChanging(value);
					this.SendPropertyChanging();
					this._department_name = value;
					this.SendPropertyChanged("department_name");
					this.Ondepartment_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_unit", DbType="NVarChar(100)")]
		public string department_unit
		{
			get
			{
				return this._department_unit;
			}
			set
			{
				if ((this._department_unit != value))
				{
					this.Ondepartment_unitChanging(value);
					this.SendPropertyChanging();
					this._department_unit = value;
					this.SendPropertyChanged("department_unit");
					this.Ondepartment_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_price", DbType="Money")]
		public System.Nullable<decimal> department_price
		{
			get
			{
				return this._department_price;
			}
			set
			{
				if ((this._department_price != value))
				{
					this.Ondepartment_priceChanging(value);
					this.SendPropertyChanging();
					this._department_price = value;
					this.SendPropertyChanged("department_price");
					this.Ondepartment_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_percentage_overtime", DbType="Int")]
		public System.Nullable<int> department_percentage_overtime
		{
			get
			{
				return this._department_percentage_overtime;
			}
			set
			{
				if ((this._department_percentage_overtime != value))
				{
					this.Ondepartment_percentage_overtimeChanging(value);
					this.SendPropertyChanging();
					this._department_percentage_overtime = value;
					this.SendPropertyChanged("department_percentage_overtime");
					this.Ondepartment_percentage_overtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ST_employees")]
	public partial class ST_employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _employee_id;
		
		private string _employee_id_custom;
		
		private string _employee_name;
		
		private string _employee_username;
		
		private string _employee_password;
		
		private string _employee_address;
		
		private string _employee_phone;
		
		private System.Nullable<System.DateTime> _employee_date_of_birth;
		
		private System.Nullable<bool> _employee_gender;
		
		private string _employee_bank_account_number;
		
		private System.Data.Linq.Binary _employee_image;
		
		private System.Nullable<long> _permission_id;
		
		private System.Nullable<long> _department_id;
		
		private System.Nullable<bool> _employee_status;
		
		private System.Nullable<System.DateTime> _employee_created_date;
		
		private System.Nullable<long> _employee_created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemployee_idChanging(long value);
    partial void Onemployee_idChanged();
    partial void Onemployee_id_customChanging(string value);
    partial void Onemployee_id_customChanged();
    partial void Onemployee_nameChanging(string value);
    partial void Onemployee_nameChanged();
    partial void Onemployee_usernameChanging(string value);
    partial void Onemployee_usernameChanged();
    partial void Onemployee_passwordChanging(string value);
    partial void Onemployee_passwordChanged();
    partial void Onemployee_addressChanging(string value);
    partial void Onemployee_addressChanged();
    partial void Onemployee_phoneChanging(string value);
    partial void Onemployee_phoneChanged();
    partial void Onemployee_date_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onemployee_date_of_birthChanged();
    partial void Onemployee_genderChanging(System.Nullable<bool> value);
    partial void Onemployee_genderChanged();
    partial void Onemployee_bank_account_numberChanging(string value);
    partial void Onemployee_bank_account_numberChanged();
    partial void Onemployee_imageChanging(System.Data.Linq.Binary value);
    partial void Onemployee_imageChanged();
    partial void Onpermission_idChanging(System.Nullable<long> value);
    partial void Onpermission_idChanged();
    partial void Ondepartment_idChanging(System.Nullable<long> value);
    partial void Ondepartment_idChanged();
    partial void Onemployee_statusChanging(System.Nullable<bool> value);
    partial void Onemployee_statusChanged();
    partial void Onemployee_created_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onemployee_created_dateChanged();
    partial void Onemployee_createdChanging(System.Nullable<long> value);
    partial void Onemployee_createdChanged();
    #endregion
		
		public ST_employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id_custom", AutoSync=AutoSync.Always, DbType="VarChar(33)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string employee_id_custom
		{
			get
			{
				return this._employee_id_custom;
			}
			set
			{
				if ((this._employee_id_custom != value))
				{
					this.Onemployee_id_customChanging(value);
					this.SendPropertyChanging();
					this._employee_id_custom = value;
					this.SendPropertyChanged("employee_id_custom");
					this.Onemployee_id_customChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_name", DbType="NVarChar(200)")]
		public string employee_name
		{
			get
			{
				return this._employee_name;
			}
			set
			{
				if ((this._employee_name != value))
				{
					this.Onemployee_nameChanging(value);
					this.SendPropertyChanging();
					this._employee_name = value;
					this.SendPropertyChanged("employee_name");
					this.Onemployee_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string employee_username
		{
			get
			{
				return this._employee_username;
			}
			set
			{
				if ((this._employee_username != value))
				{
					this.Onemployee_usernameChanging(value);
					this.SendPropertyChanging();
					this._employee_username = value;
					this.SendPropertyChanged("employee_username");
					this.Onemployee_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_password", DbType="VarChar(255)")]
		public string employee_password
		{
			get
			{
				return this._employee_password;
			}
			set
			{
				if ((this._employee_password != value))
				{
					this.Onemployee_passwordChanging(value);
					this.SendPropertyChanging();
					this._employee_password = value;
					this.SendPropertyChanged("employee_password");
					this.Onemployee_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_address", DbType="NVarChar(255)")]
		public string employee_address
		{
			get
			{
				return this._employee_address;
			}
			set
			{
				if ((this._employee_address != value))
				{
					this.Onemployee_addressChanging(value);
					this.SendPropertyChanging();
					this._employee_address = value;
					this.SendPropertyChanged("employee_address");
					this.Onemployee_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_phone", DbType="NVarChar(255)")]
		public string employee_phone
		{
			get
			{
				return this._employee_phone;
			}
			set
			{
				if ((this._employee_phone != value))
				{
					this.Onemployee_phoneChanging(value);
					this.SendPropertyChanging();
					this._employee_phone = value;
					this.SendPropertyChanged("employee_phone");
					this.Onemployee_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> employee_date_of_birth
		{
			get
			{
				return this._employee_date_of_birth;
			}
			set
			{
				if ((this._employee_date_of_birth != value))
				{
					this.Onemployee_date_of_birthChanging(value);
					this.SendPropertyChanging();
					this._employee_date_of_birth = value;
					this.SendPropertyChanged("employee_date_of_birth");
					this.Onemployee_date_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_gender", DbType="Bit")]
		public System.Nullable<bool> employee_gender
		{
			get
			{
				return this._employee_gender;
			}
			set
			{
				if ((this._employee_gender != value))
				{
					this.Onemployee_genderChanging(value);
					this.SendPropertyChanging();
					this._employee_gender = value;
					this.SendPropertyChanged("employee_gender");
					this.Onemployee_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_bank_account_number", DbType="NVarChar(255)")]
		public string employee_bank_account_number
		{
			get
			{
				return this._employee_bank_account_number;
			}
			set
			{
				if ((this._employee_bank_account_number != value))
				{
					this.Onemployee_bank_account_numberChanging(value);
					this.SendPropertyChanging();
					this._employee_bank_account_number = value;
					this.SendPropertyChanged("employee_bank_account_number");
					this.Onemployee_bank_account_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary employee_image
		{
			get
			{
				return this._employee_image;
			}
			set
			{
				if ((this._employee_image != value))
				{
					this.Onemployee_imageChanging(value);
					this.SendPropertyChanging();
					this._employee_image = value;
					this.SendPropertyChanged("employee_image");
					this.Onemployee_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", DbType="BigInt")]
		public System.Nullable<long> permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this.Onpermission_idChanging(value);
					this.SendPropertyChanging();
					this._permission_id = value;
					this.SendPropertyChanged("permission_id");
					this.Onpermission_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", DbType="BigInt")]
		public System.Nullable<long> department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_status", DbType="Bit")]
		public System.Nullable<bool> employee_status
		{
			get
			{
				return this._employee_status;
			}
			set
			{
				if ((this._employee_status != value))
				{
					this.Onemployee_statusChanging(value);
					this.SendPropertyChanging();
					this._employee_status = value;
					this.SendPropertyChanged("employee_status");
					this.Onemployee_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> employee_created_date
		{
			get
			{
				return this._employee_created_date;
			}
			set
			{
				if ((this._employee_created_date != value))
				{
					this.Onemployee_created_dateChanging(value);
					this.SendPropertyChanging();
					this._employee_created_date = value;
					this.SendPropertyChanged("employee_created_date");
					this.Onemployee_created_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_created", DbType="BigInt")]
		public System.Nullable<long> employee_created
		{
			get
			{
				return this._employee_created;
			}
			set
			{
				if ((this._employee_created != value))
				{
					this.Onemployee_createdChanging(value);
					this.SendPropertyChanging();
					this._employee_created = value;
					this.SendPropertyChanged("employee_created");
					this.Onemployee_createdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
